### ISSUE TITLE
Wrong repository URL

### ISSUE THREAD

**Issue by rkaldung** [znuny/ITSM#1]
See https://github.com/znuny/ITSMCore/issues/1 also applies to this package with different URL: https://github.com/znuny/ITSM/blob/rel-6_0/Kernel/Config/Files/XML/FrameworkITSM.xml

**Comment by dennykorsukewitz** [comment]
Fixed with: https://github.com/znuny/ITSM/commit/522c0521a92c32bc1496fa0e185ddb89ddba2950
